[package]
name = "tracing_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = {version = "0.3.20", features = ["chrono"]}
tracing-tree = "0.4.0"
